package stattleship

const AllStarInterval string = "allstar"
const ConferenceChampionshipInterval string = "conferencechampionship"
const ConferenceQuarterFinalsInterval string = "conferencequarterfinals"
const ConferenceSemiFinalsInterval string = "conferencesemifinals"
const ConferenceFinalsInterval string = "conferencefinals"
const DivisionalPlayoffsInterval string = "divisionalplayoffs"
const DivisionalPlayoffInterval string = "divisionalplayoff"
const LeagueChampionshipInterval string = "leaguechampionship"
const NBAChampionshipInterval string = "nbachampionship"
const PostponedInterval string = "postponed"
const PreseasonInterval string = "preseason"
const PreseasonHallOfFameWeekInterval string = "preseasonhalloffameweek"
const PreseasonWeekInterval string = "preseasonweek"
const ProBowlInterval string = "probowl"
const RegularSeasonInterval string = "regularseason"
const RisingStarsChallengeInterval string = "risingstarschallenge"
const StanleyCupFinalsInterval string = "stanleycupfinals"
const SuperBowlInterval string = "superbowl"
const WeekInterval string = "week"
const WildCardInterval string = "wildcard"
const WildCardShowdownInterval string = "wildcardshowdown"
const WorldSeriesInterval string = "worldseries"
